# use the official node.js 18 image with alphine linux as base image
FROM node:18-alphine

WORKDIR /use/src/app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

EXPOSE 3003

CMD [ "node","src/server.js" ]